default:
  image: node:15.10.0-slim

stages:
  - lint
  - test
  - upload
  - migrate
  - deploy

install:
  stage: .pre
  inherit:
    default: [image]
  script: npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/

lint:
  stage: lint
  needs: [install]
  inherit:
    default: [image]
  script: npm run lint

test:
  stage: test
  needs: [install]
  inherit:
    default: [image]
  before_script:
    - cat $TESTING_ENV_FILE > .env
  script:
    - npm run migrate
    - npm run test
    - npm run schema:drop:test

.upload_template: &upload
  stage: upload
  needs: [lint, test]
  image: docker:20.10.5
  services:
    - docker:20.10.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://$DOCKER_REGISTRY < gcloud-service-key.json
    - docker build -t $DOCKER_IMAGE-$NODE_ENV -f Dockerfile.production .
    - docker tag $DOCKER_IMAGE-$NODE_ENV $DOCKER_REGISTRY/$GCP_PROJECT_ID/$DOCKER_IMAGE-$NODE_ENV
    - docker push $DOCKER_REGISTRY/$GCP_PROJECT_ID/$DOCKER_IMAGE-$NODE_ENV
  after_script:
    - rm gcloud-service-key.json
    - rm .env

upload:staging:
  <<: *upload
  only: [staging]
  variables:
    NODE_ENV: staging
  before_script:
    - cat $STAGING_ENV_FILE > .env

upload:production:
  <<: *upload
  only: [master]
  variables:
    NODE_ENV: production
  before_script:
    - cat $PRODUCTION_ENV_FILE > .env

.migrate-template: &migrate
  stage: migrate
  inherit:
    default: [image]
  script: npm run migrate
  after_script:
    - rm .env

migrate:staging:
  <<: *migrate
  only: [staging]
  before_script:
    - cat $STAGING_ENV_FILE > .env

migrate:production:
  <<: *migrate
  only: [master]
  before_script:
    - cat $PRODUCTION_ENV_FILE > .env

.deploy-template: &deploy
  stage: deploy
  image: google/cloud-sdk
  before_script:
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
  script:
    - gcloud run deploy $DOCKER_IMAGE-$NODE_ENV --image $DOCKER_REGISTRY/$GCP_PROJECT_ID/$DOCKER_IMAGE-$NODE_ENV --project $GCP_PROJECT_ID --region us-central1 --platform managed --allow-unauthenticated
  after_script:
    - rm gcloud-service-key.json

deploy:staging:
  <<: *deploy
  only: [staging]
  needs: ["upload:staging"]
  variables:
    NODE_ENV: staging

deploy:production:
  <<: *deploy
  only: [master]
  needs: ["upload:production"]
  variables:
    NODE_ENV: production
