language: node_js
node_js:
  - node

services:
  - postgresql

env:
  NODE_ENV=testing
  NODE_PORT=4000
  PRODUCTION_ENV=production
  DATABASE_TYPE=postgres
  DATABASE_HOST=0.0.0.0
  DATABASE_PORT=5432
  DATABASE_NAME=testing
  DATABASE_USER=postgres

install:
  - npm ci

before_script:
  - psql --command "CREATE DATABASE ${DATABASE_NAME};" -U postgres

script:
  - npm run lint
  - npm test