language: node_js
node_js:
  - node

services:
  - postgresql

env:
  NODE_ENV=testing
  PRODUCTION_ENV=production
  DATABASE_NAME=testing

install:
  - npm ci

before_script:
  - psql --command "CREATE DATABASE ${DATABASE_NAME};" -U postgres

script:
  - npm run lint
  - npm test