FROM node:16-slim

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# For production
RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 4000

CMD npm run start:production