import { Types } from '../../interfaces/types';

const {
  NOT_FOUND,
  CATEGORY,
  ETYMOLOGY,
  OPTION,
  PATTERN,
  QUESTION,
  REFERENCE,
  TEST,
  USER,
  VERSION,
  WORD,
} = {
  NOT_FOUND: ' not found!',
  CATEGORY: 'Category',
  ETYMOLOGY: 'Etymology',
  OPTION: 'Option',
  PATTERN: 'Pattern',
  QUESTION: 'Question',
  REFERENCE: 'Reference',
  TEST: 'Test',
  USER: 'User',
  VERSION: 'Version',
  WORD: 'Word',
};

const PARAMS = {
  ID_PARAM: 'id',
  DATA_PARAM: 'data',
};

const { VARCHAR, BOOLEAN, TIMESTAMP }: Types = {
  VARCHAR: { type: 'varchar' },
  BOOLEAN: { type: 'boolean' },
  TIMESTAMP: { type: 'timestamp' },
};

const {
  XXS, XS, S, M, L, XL, XXL, XXXXL,
} = {
  XXS: 4,
  XS: 8,
  S: 16,
  M: 32,
  L: 64,
  XL: 128,
  XXL: 256,
  XXXXL: 1024,
};

const DATABASE_CONFIG = {
  BOOLEAN_DEFAULT_TRUE: { ...BOOLEAN, default: true },
  BOOLEAN_DEFAULT_FALSE: { ...BOOLEAN, default: false },
  VARCHAR_XXS: { ...VARCHAR, length: XXS },
  VARCHAR_XS: { ...VARCHAR, length: XS },
  VARCHAR_S: { ...VARCHAR, length: S },
  VARCHAR_M: { ...VARCHAR, length: M },
  VARCHAR_L: { ...VARCHAR, length: L },
  VARCHAR_XL: { ...VARCHAR, length: XL },
  VARCHAR_XXL: { ...VARCHAR, length: XXL },
  VARCHAR_XXXXL: { ...VARCHAR, length: XXXXL },
  VARCHAR_S_UNIQUE: { ...VARCHAR, length: S, unique: true },
  VARCHAR_L_UNIQUE: { ...VARCHAR, length: L, unique: true },
  VARCHAR_XXL_UNIQUE: { ...VARCHAR, length: XXL, unique: true },
  VARCHAR_XXXXL_UNIQUE: { ...VARCHAR, length: XXXXL, unique: true },
  TIMESTAMP_DEFAULT: TIMESTAMP,
  NULLABLE: { nullable: true },
};

const TESTS_NUMBERS = {
  FAKER_ELEMENTS_NUMBER_S: 4,
  FAKER_ELEMENTS_NUMBER_M: 7,
  FAKER_ELEMENTS_NUMBER_L: 10,
  FAKER_ELEMENTS_NUMBER_XL: 99,
  FAKER_ELEMENTS_NUMBER_XXL: 9999,
  INEXISTENT_INDEX: 1452902144,
};

const TEST_OPTIONS = {
  DUMMY_TEXT_XS: 'Lorem',
  DUMMY_TEXT2_XS: 'Lorems',
  DUMMY_TEXT_S: 'Lorem ipsum dolor sit amet',
  DUMMY_TEXT_M: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  DUMMY_TEXT_L:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a odio at metus egestas commodo. Quisque vel imperdiet tellus. Morbi eu ante efficitur, congue justo maximus, sollicitudin velit. Fusce at pharetra lectus. Fusce neque urna, rutrum in quam vitae, condimentum mattis turpis. Praesent accumsan lobortis sollicitudin.',
  DUMMY_TEXT_XL:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a odio at metus egestas commodo. Quisque vel imperdiet tellus. Morbi eu ante efficitur, congue justo maximus, sollicitudin velit. Fusce at pharetra lectus. Fusce neque urna, rutrum in quam vitae, condimentum mattis turpis. Praesent accumsan lobortis sollicitudin. Vestibulum urna libero, gravida in lorem sit amet, ultricies volutpat diam. Mauris cursus eros elit, vestibulum vehicula libero ultrices at. Curabitur sed lectus nec lectus iaculis varius iaculis sed augue. Ut ut diam eget nibh gravida varius id in risus. Curabitur vel ultrices quam. Quisque viverra in erat ut molestie. Vestibulum rhoncus sapien sit amet iaculis fermentum. Fusce sagittis blandit nisi ut consectetur. Sed eget ultrices ante, sit amet luctus justo. Donec elit enim, venenatis eu magna at, faucibus scelerisque mauris. In ut tempor urna. Duis posuere ligula odio. Morbi a condimentum felis. Cras auctor, tortor eget condimentum dignissim, eros enim laoreet lectus, ut hendrerit leo nulla eu est. Sed vitae luctus dui, sit amet blandit ante. Vestibulum bibendum massa odio. Nulla sit amet arcu sit amet neque condimentum iaculis. Donec elementum risus in congue gravida. Donec auctor lacus eget libero rutrum, ultricies vestibulum dolor lobortis. Nam egestas id lacus ornare vehicula. Aenean hendrerit massa quam, sit amet tristique nibh sodales a. Vivamus efficitur metus velit, et pulvinar nunc fermentum ut. Mauris porta massa eu elit sollicitudin vulputate. Etiam finibus tincidunt sagittis. Nam tortor neque, fringilla et est sed, semper tempor odio. Proin sit amet nibh quis turpis porta dictum at rutrum tellus. Aliquam sed tempus leo. Nulla tincidunt a est volutpat ornare. In hac habitasse platea dictumst. Nunc vel tristique augue. Vestibulum bibendum lorem non odio mollis rutrum. Nulla sagittis egestas bibendum. Nulla mauris metus, tristique sit amet turpis a, vehicula tincidunt lorem. Mauris feugiat tortor in sem tempus tempus. Curabitur velit lorem, bibendum a congue vitae, ultricies nec nulla.',
  DUMMY_IMAGE_URL:
    'https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/d2/88/6d/d2886d3d-f03c-d0fa-1277-540ee369a194/source/512x512bb.jpg',
  DUMMY_EMAIL: 'test@mail.com',
  DUMMY_EMAIL2: 'test2@mail.com',
  DUMMY_YEAR_STRING: '1999',
  DUMMY_VERSION_STRING: '1.1.9',
  DUMMY_VERSION2_STRING: '2.3.7',
};

const TEST_OBJECTS = {
  ...TEST_OPTIONS,
  DUMMY_CATEGORY: {
    name: TEST_OPTIONS.DUMMY_TEXT_XS,
    description: TEST_OPTIONS.DUMMY_TEXT_M,
    active: true,
  },
  DUMMY_CATEGORY2: {
    name: TEST_OPTIONS.DUMMY_TEXT2_XS,
    description: TEST_OPTIONS.DUMMY_TEXT_M,
    active: true,
  },
  DUMMY_CATEGORY_INCORRECT: {
    name: TEST_OPTIONS.DUMMY_TEXT_XL,
    description: TEST_OPTIONS.DUMMY_TEXT_M,
    active: true,
  },
  DUMMY_ETYMOLOGY: {
    graecoLatinEtymology: TEST_OPTIONS.DUMMY_TEXT_XS,
    meaning: TEST_OPTIONS.DUMMY_TEXT_M,
    imageUrl: TEST_OPTIONS.DUMMY_IMAGE_URL,
    etymologyTypeId: 1,
    languageId: 1,
    active: true,
  },
  DUMMY_ETYMOLOGY2: {
    graecoLatinEtymology: TEST_OPTIONS.DUMMY_TEXT2_XS,
    meaning: TEST_OPTIONS.DUMMY_TEXT_M,
    imageUrl: TEST_OPTIONS.DUMMY_IMAGE_URL,
    etymologyTypeId: 1,
    languageId: 1,
    active: true,
  },
  DUMMY_ETYMOLOGY_INCORRECT: {
    graecoLatinEtymology: TEST_OPTIONS.DUMMY_TEXT_XL,
    meaning: TEST_OPTIONS.DUMMY_TEXT_M,
    imageUrl: TEST_OPTIONS.DUMMY_IMAGE_URL,
    etymologyTypeId: 1,
    languageId: 1,
    active: true,
  },
  DUMMY_OPTION: {
    option: TEST_OPTIONS.DUMMY_TEXT_XS,
    correct: true,
    active: true,
  },
  DUMMY_OPTION2: {
    option: TEST_OPTIONS.DUMMY_TEXT2_XS,
    correct: true,
    active: true,
  },
  DUMMY_OPTION_INCORRECT: {
    option: TEST_OPTIONS.DUMMY_TEXT_XL,
    correct: true,
    active: true,
  },
  DUMMY_PATTERN: {
    pattern: TEST_OPTIONS.DUMMY_TEXT_XS,
    active: true,
  },
  DUMMY_PATTERN2: {
    pattern: TEST_OPTIONS.DUMMY_TEXT2_XS,
    active: true,
  },
  DUMMY_PATTERN_INCORRECT: {
    pattern: TEST_OPTIONS.DUMMY_TEXT_XL,
    active: true,
  },
  DUMMY_QUESTION: {
    sentence: TEST_OPTIONS.DUMMY_TEXT_L,
    active: false,
    referenceId: 1,
  },
  DUMMY_QUESTION2: {
    sentence: TEST_OPTIONS.DUMMY_TEXT2_XS,
    active: false,
    referenceId: 1,
  },
  DUMMY_QUESTION_INCORRECT: {
    sentence: TEST_OPTIONS.DUMMY_TEXT_XL,
    active: false,
    referenceId: 1,
  },
  DUMMY_REFERENCE: {
    author: TEST_OPTIONS.DUMMY_TEXT_M,
    title: TEST_OPTIONS.DUMMY_TEXT_M,
    publicationYear: TEST_OPTIONS.DUMMY_YEAR_STRING,
    publicationPlace: TEST_OPTIONS.DUMMY_TEXT_M,
    publishingCompany: TEST_OPTIONS.DUMMY_TEXT_M,
    active: false,
  },
  DUMMY_REFERENCE2: {
    author: TEST_OPTIONS.DUMMY_TEXT_M,
    title: TEST_OPTIONS.DUMMY_TEXT2_XS,
    publicationYear: TEST_OPTIONS.DUMMY_YEAR_STRING,
    publicationPlace: TEST_OPTIONS.DUMMY_TEXT_M,
    publishingCompany: TEST_OPTIONS.DUMMY_TEXT_M,
    active: false,
  },
  DUMMY_REFERENCE_INCORRECT: {
    author: TEST_OPTIONS.DUMMY_TEXT_M,
    title: TEST_OPTIONS.DUMMY_TEXT_XL,
    publicationYear: TEST_OPTIONS.DUMMY_YEAR_STRING,
    publicationPlace: TEST_OPTIONS.DUMMY_TEXT_M,
    publishingCompany: TEST_OPTIONS.DUMMY_TEXT_M,
    active: false,
  },
  DUMMY_TEST: {
    userId: 1,
    questionId: 1,
    active: true,
  },
  DUMMY_TEST2: {
    userId: 1,
    questionId: 1,
    active: false,
  },
  DUMMY_USER: {
    name: TEST_OPTIONS.DUMMY_TEXT_M,
    email: TEST_OPTIONS.DUMMY_EMAIL,
    active: true,
  },
  DUMMY_USER2: {
    name: TEST_OPTIONS.DUMMY_TEXT2_XS,
    email: TEST_OPTIONS.DUMMY_EMAIL2,
    active: true,
  },
  DUMMY_USER_INCORRECT: {
    name: TEST_OPTIONS.DUMMY_TEXT_XL,
    email: TEST_OPTIONS.DUMMY_EMAIL,
    active: true,
  },
  DUMMY_VERSION: {
    version: TEST_OPTIONS.DUMMY_VERSION_STRING,
    description: TEST_OPTIONS.DUMMY_TEXT_M,
    maintenance: false,
    active: true,
  },
  DUMMY_VERSION2: {
    version: TEST_OPTIONS.DUMMY_VERSION2_STRING,
    description: TEST_OPTIONS.DUMMY_TEXT_M,
    maintenance: false,
    active: true,
  },
  DUMMY_VERSION_INCORRECT: {
    version: TEST_OPTIONS.DUMMY_TEXT_XL,
    description: TEST_OPTIONS.DUMMY_TEXT_M,
    maintenance: false,
    active: true,
  },
  DUMMY_WORD: {
    word: TEST_OPTIONS.DUMMY_TEXT_XS,
    meaning: TEST_OPTIONS.DUMMY_TEXT_M,
    imageUrl: TEST_OPTIONS.DUMMY_IMAGE_URL,
    categoryId: 1,
    active: true,
  },
  DUMMY_WORD2: {
    word: TEST_OPTIONS.DUMMY_TEXT2_XS,
    meaning: TEST_OPTIONS.DUMMY_TEXT_M,
    imageUrl: TEST_OPTIONS.DUMMY_IMAGE_URL,
    categoryId: 1,
    active: true,
  },
  DUMMY_WORD_INCORRECT: {
    word: TEST_OPTIONS.DUMMY_TEXT_XL,
    meaning: TEST_OPTIONS.DUMMY_TEXT_M,
    imageUrl: TEST_OPTIONS.DUMMY_IMAGE_URL,
    categoryId: 1,
    active: true,
  },
};

const MESSAGES = {
  CATEGORY_NOT_FOUND: `${CATEGORY}${NOT_FOUND}`,
  ETYMOLOGY_NOT_FOUND: `${ETYMOLOGY}${NOT_FOUND}`,
  OPTION_NOT_FOUND: `${OPTION}${NOT_FOUND}`,
  PATTERN_NOT_FOUND: `${PATTERN}${NOT_FOUND}`,
  QUESTION_NOT_FOUND: `${QUESTION}${NOT_FOUND}`,
  REFERENCE_NOT_FOUND: `${REFERENCE}${NOT_FOUND}`,
  TEST_NOT_FOUND: `${TEST}${NOT_FOUND}`,
  USER_NOT_FOUND: `${USER}${NOT_FOUND}`,
  VERSION_NOT_FOUND: `${VERSION}${NOT_FOUND}`,
  WORD_NOT_FOUND: `${WORD}${NOT_FOUND}`,
  ERROR_MAX_LENGTH: 'value too long for type character varying',
  ERROR_DUPLICATE_KEY: 'duplicate key value violates unique constraint',
};

const CONSTANTS = {
  ...PARAMS,
  ...DATABASE_CONFIG,
  ...TESTS_NUMBERS,
  ...TEST_OBJECTS,
  ...MESSAGES,
};

export const {
  ID_PARAM,
  DATA_PARAM,
  BOOLEAN_DEFAULT_TRUE,
  BOOLEAN_DEFAULT_FALSE,
  VARCHAR_XXS,
  VARCHAR_XS,
  VARCHAR_S,
  VARCHAR_M,
  VARCHAR_L,
  VARCHAR_XL,
  VARCHAR_XXL,
  VARCHAR_XXXXL,
  VARCHAR_S_UNIQUE,
  VARCHAR_L_UNIQUE,
  VARCHAR_XXL_UNIQUE,
  VARCHAR_XXXXL_UNIQUE,
  TIMESTAMP_DEFAULT,
  NULLABLE,
  FAKER_ELEMENTS_NUMBER_S,
  FAKER_ELEMENTS_NUMBER_M,
  FAKER_ELEMENTS_NUMBER_L,
  FAKER_ELEMENTS_NUMBER_XL,
  FAKER_ELEMENTS_NUMBER_XXL,
  INEXISTENT_INDEX,
  DUMMY_TEXT_XS,
  DUMMY_TEXT2_XS,
  DUMMY_TEXT_S,
  DUMMY_TEXT_M,
  DUMMY_TEXT_L,
  DUMMY_TEXT_XL,
  DUMMY_IMAGE_URL,
  DUMMY_EMAIL,
  DUMMY_EMAIL2,
  DUMMY_YEAR_STRING,
  DUMMY_VERSION_STRING,
  DUMMY_VERSION2_STRING,
  DUMMY_CATEGORY,
  DUMMY_CATEGORY2,
  DUMMY_CATEGORY_INCORRECT,
  DUMMY_ETYMOLOGY,
  DUMMY_ETYMOLOGY2,
  DUMMY_ETYMOLOGY_INCORRECT,
  DUMMY_OPTION,
  DUMMY_OPTION2,
  DUMMY_OPTION_INCORRECT,
  DUMMY_PATTERN,
  DUMMY_PATTERN2,
  DUMMY_PATTERN_INCORRECT,
  DUMMY_QUESTION,
  DUMMY_QUESTION2,
  DUMMY_QUESTION_INCORRECT,
  DUMMY_REFERENCE,
  DUMMY_REFERENCE2,
  DUMMY_REFERENCE_INCORRECT,
  DUMMY_TEST,
  DUMMY_TEST2,
  DUMMY_USER,
  DUMMY_USER2,
  DUMMY_USER_INCORRECT,
  DUMMY_VERSION,
  DUMMY_VERSION2,
  DUMMY_VERSION_INCORRECT,
  DUMMY_WORD,
  DUMMY_WORD2,
  DUMMY_WORD_INCORRECT,
  CATEGORY_NOT_FOUND,
  ETYMOLOGY_NOT_FOUND,
  OPTION_NOT_FOUND,
  PATTERN_NOT_FOUND,
  QUESTION_NOT_FOUND,
  REFERENCE_NOT_FOUND,
  TEST_NOT_FOUND,
  USER_NOT_FOUND,
  VERSION_NOT_FOUND,
  WORD_NOT_FOUND,
  ERROR_MAX_LENGTH,
  ERROR_DUPLICATE_KEY,
} = CONSTANTS;
